name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: chess-game:latest
        outputs: type=docker,dest=/tmp/chess-game.tar
        
    - name: Copy Docker image to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "/tmp/chess-game.tar"
        target: "/home/ubuntu"
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Load the Docker image
          docker load < /home/ubuntu/chess-game.tar
          
          # Stop any running container
          docker stop chess-game || true
          docker rm chess-game || true
          
          # Run the new container
          docker run -d --name chess-game -p 80:8000 \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --restart always \
            chess-game:latest
          
          # Clean up
          rm /home/ubuntu/chess-game.tar
